package main

import (
	"context"
	"os"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"go.opentelemetry.io/otel/trace"
	"job4j.ru/share_trip/internal/observability/metrics"
	"job4j.ru/share_trip/internal/observability/tracing"

	"github.com/jackc/pgx/v5/pgxpool"
	applog "job4j.ru/share_trip/internal/app"
	"job4j.ru/share_trip/internal/domain/trip/usecase"
	"job4j.ru/share_trip/internal/middleware"

	"github.com/go-playground/validator/v10"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/log"
	"github.com/joho/godotenv"
	"job4j.ru/share_trip/configs"
	"job4j.ru/share_trip/internal/api"
	"job4j.ru/share_trip/internal/repository"
	"job4j.ru/share_trip/internal/service"
	"job4j.ru/share_trip/internal/storage"
)

// init is invoked before main()
func init() {
	// loads values from .env into the system
	if err := godotenv.Load(); err != nil {
		log.Info("No .env file found")
	}
}

func main() {
	ctx := context.Background()

	cfg := readCfg()

	pool, err := storage.NewPool(ctx, cfg.DSN())
	if err != nil {
		log.Fatal(err)
	}

	defer pool.Close()

	// logging connection to DB
	if pingErr := pool.Ping(ctx); pingErr != nil {
		log.Fatalf("failed to ping database: %v", pingErr)
	}
	log.Info("Connected to database successfully")

	//logger
	logger, logFile, err := applog.NewLogger()
	if err != nil {
		panic(err)
	}
	defer func(logFile *os.File) {
		err := logFile.Close()
		if err != nil {
			log.Fatal(err)
		}
	}(logFile)

	//registry Prometheus
	registry := prometheus.NewRegistry()
	m := metrics.New(registry)

	// init Tracing (OpenTelemetry → otel-collector → Jaeger)
	tp, err := initTracing(ctx)
	if err != nil {
		log.Error("init tracing failed", "error", err)
		os.Exit(1)
	}
	defer func() {
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		if shutdownErr := tp.Shutdown(shutdownCtx); shutdownErr != nil {
			log.Error("shutdown tracing failed", "error", shutdownErr)
		}
	}()

	//app
	app := fiber.New(fiber.Config{
		EnablePrintRoutes: true,
	})
	app.Use(tracing.NewFiberMiddleware()) // init Tracing OpenTelemetry
	app.Use(func(c *fiber.Ctx) error {
		log.Infof("Generated ID: %v", c.Locals("requestid"))

		ctx := c.UserContext()
		// Extracting the TraceID generated by OpenTelemetry
		traceID := trace.SpanFromContext(ctx).SpanContext().TraceID().String()
		// Set it as the Request-ID in the response so the client can see it            c.Set("X-Request-ID", traceID)
		c.Set("X-Request-ID", traceID)
		// Save in locals if needed locally within Fiber		c.Locals("requestid", traceID)
		c.Locals("requestid", traceID)

		return c.Next()
	})
	//add custom logger, before add api and metrics
	app.Use(middleware.Correlation(logger))
	//add metrics middleware
	app.Use(api.NewHTTPMetricsMiddleware(m))

	//set keycloak to app
	setKeycloakToApp(app)

	//build Server
	build(app, pool, registry, m)

	//listen app
	err = app.Listen(":8080")
	if err != nil {
		log.Fatal("failed to listen: %v", err)
	}
}

// build - build server
func build(
	app *fiber.App,
	pool *pgxpool.Pool,
	registry *prometheus.Registry,
	m *metrics.Metrics,
) {
	// Initialize the validator instance
	validate := validator.New(validator.WithRequiredStructEnabled())

	repo := repository.NewRepoPg(pool)
	repoTrip := repository.NewTripRepository(m, pool)
	outboxRepo := repository.NewOutboxEventRepository()

	infoUseCase := usecase.NewInfoUseCase()
	tripUseCase := usecase.NewTripUseCase()

	infoService := service.NewInfoService(infoUseCase, repo)
	tripService := service.NewTripService(m, pool, repoTrip, outboxRepo, tripUseCase)

	server := api.NewServer(registry, validate, infoService, tripService) // ← add all service`s

	//route
	server.SetupRoutes(app)
}

func readCfg() storage.Config {
	return storage.Config{
		Host:     configs.Env("DB_HOST", "localhost"),
		Port:     configs.EnvInt("DB_PORT", 6543),
		User:     configs.Env("DB_USER", "postgres"),
		Password: configs.Env("DB_PASSWORD", "password"),
		DBName:   configs.Env("DB_NAME", "share_trip"),
		SSLMode:  configs.Env("DB_SSLMODE", "disable"),
	}
}

func initTracing(ctx context.Context) (*tracing.TracerProvider, error) {
	return tracing.NewProvider(ctx, tracing.Config{
		ServiceName:    configs.Env("OTEL_SERVICE_NAME", "share-trip"),
		ServiceVersion: configs.Env("OTEL_SERVICE_VERSION", "1.0.0"),
		Environment:    configs.Env("OTEL_ENVIRONMENT", "local"),
		Endpoint:       configs.Env("OTEL_EXPORTER_ENDPOINT", "localhost:4319"),
	})
}

func setKeycloakToApp(app *fiber.App) {
	app.Use(middleware.KeycloakRefreshTokenMiddleware(
		middleware.KeycloakConfig{
			Issuer:       configs.Env("KEYCLOAK_ISSUER", "http://localhost:8087/realms/sharetrip"), // issuer of the keycloak server, he must point to the realm (http://localhost:8087/realms/your-realm)
			ClientID:     configs.Env("KEYCLOAK_CLIENT_ID", "sharetrip-api"),                       // client id of the client, it is used to authenticate the client to the keycloak server
			ClientSecret: configs.Env("KEYCLOAK_CLIENT_SECRET", "secret"),                          // client secret of the client, it is used to authenticate the client to the keycloak server
		},
	))
}
