version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: pg_trip
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: share_trip
    ports:
      - "6543:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data:
